### PR TITLE
Add Stackbit Integration

### PR DESCRIPTION
**Pull request by DarkoArnautov**
This pull request add's Stackbit to this Hugo theme. It add's the stackbit.yaml file which makes this theme work with several headless CMS automatically (including Forestry, NetlifyCMS, DatoCMS & Contentful) and it deploys the site to Netlify in 1 click.

You can try it out: https://app.stackbit.com/create?theme=https://github.com/stackbithq/aether (note the "create with stackbit" button in the readme will import the theme from your repo so until the PR is merged it wont work)

I think this is really valuable and is a very low impact addition on your existing theme structure. Pretty much just the stackbit.yaml file. If you have questions or feedback I'm happy to discuss.

Darko

### CODE REVIEW

**Comment by josephhutch** [comment]
Why did you have to add the images to the examplesite/static/img folder?

**Comment by DarkoArnautov** [comment]
Hello, josephhutch.
The reason that images needs to proceed with upload folder in headless CMS.
In order to do that, it should be placed in one folder.
static/img or exampleSite/static/img.
Then user can upload image and edit content with GUI in the headless CMS.
Thank you.

**Comment by Chevindu** [comment]
@josephhutch Hey, I was wondering why this PR was not merged. Your theme is very clean and I think it'd be amazing to have it working with a CMS.

**Comment by josephhutch** [comment]
@DarkoArnautov Can you make sure this theme still works with Stackbit.  If so, I will merge the pr.  It has been a while so I don't want to add support if it doesn't work.

**Comment by josephhutch** [comment]
@DarkoArnautov because the changes are not consistent with the use of page bundles, I will not be merging these changes with the theme.

**Pull request closed without merging**
