### PR TITLE
using pre tag render unhighlighted code block.

### PR DESCRIPTION
**Pull request by cntrump**
Because of highlightjs [The CDN-hosted package doesn't have all the languages.](https://github.com/isagalaev/highlight.js#getting-the-library)

yaml code block look like this:

```
static/css/main.min.css
```

move some styles from `code` to `pre` tag

```css
pre{padding:.2em .5em;border-radius:.3rem;background-color:#f3f3f3}code{font-family:monospace;line-height:1.5}
```

Now, It looks like this:

@josephhutch do you have other better way ?

### CODE REVIEW

**Comment by josephhutch** [comment]
Hey @cntrump,
If highlight.js does not support a language then there is no reason to specify the language because it will just prevent it from rendering correctly.  Changing the style on `pre` could have unintended side effects.  I'm going to investigate a fix but an easy work around is to not include the language, just use the triple back-tick.
````
```
code here
```
````

**Comment by cntrump** [comment]
This problem also existed before highlight.js loading, I think the css can be improved.

**Comment by josephhutch** [comment]
@cntrump, instead of the above style change, the following would be more safe and just as robust.
```css
pre > code {
    display: block;
    padding: 0.5em;
}
```

**Comment by cntrump** [comment]
I copied some styles from github markdown css

```css
code {
    background-color: rgba(27,31,35,.05);
    border-radius: 3px;
    font-size: 85%;
    margin: 0;
    padding: .2em .4em;
}

pre {
    word-wrap: normal;
}

pre>code {
    background: transparent;
    border: 0;
    font-size: 100%;
    margin: 0;
    padding: 0;
    white-space: pre;
    word-break: normal;
}

pre {
    background-color: #f6f8fa;
    border-radius: 3px;
    font-size: 85%;
    line-height: 1.45;
    overflow: auto;
    padding: 16px;
}

pre code {
    background-color: transparent;
    border: 0;
    display: inline;
    line-height: inherit;
    margin: 0;
    max-width: auto;
    overflow: visible;
    padding: 0;
    word-wrap: normal;
}
```

**Comment by cntrump** [comment]
I add an option ‘hljsCSS’, support custom highlightjs theme is funny.😁

**Comment by josephhutch** [comment]
I fixed the issue you described in your initial pull request comment in commits 21e546d1cc527e7e46320f2008d55ba25bbed24b and b5cb9ffdf6c9e991f933784187b238220cbc7157.  There are too many issues with this pull request and there are too many different changes to accept it. For instance all local css should be minified in the main.min.css file. Also, GitHub's CSS does not fit the style of this theme.

**Comment by cntrump** [comment]
Thanks, I merged your fix to my fork.

**Pull request closed without merging**
